# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
project_name: packer


before:
  hooks:
    # this is just an example and not a requirement for provider building/publishing
    - make fmt-check generate-check

dist: "./pkg"


builds:
  - env:
      # goreleaser does not work with CGO, it could also complicate
      # usage by users in CI/CD systems like Terraform Cloud where
      # they are unable to install libraries.
      - CGO_ENABLED=0
    # mod_timestamp: '{{ .CommitTimestamp }}'
    dir: .
    flags:
      - -trimpath
    ldflags:
      - '-X github.com/hashicorp/packer/version.GitCommit={{ .ShortCommit }} -s -w'
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      # - arm
      # - arm64
    ignore:
      - goos: darwin
        goarch: "386"
    binary: "{{ .ProjectName }}"

changelog:
  skip: true

release:
  disable: true

checksum:
  disable: true
archives:
- format: zip
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  files:
    - none*

blobs:
  # You can have multiple blob configs
  -
    # Template for the cloud provider name
    # s3 for AWS S3 Storage
    # azblob for Azure Blob Storage
    # gs for Google Cloud Storage
    provider: s3

    # Set a custom endpoint, useful if you're using a minio backend or
    # other s3-compatible backends.
    # Implies s3ForcePathStyle and requires provider to be `s3`
    endpoint: https://storage.cloud-preprod.yandex.net

    # Sets the bucket region.
    # Requires provider to be `s3`
    # Defaults to empty.
    region: ru-central1

    # Disables SSL
    # Requires provider to be `s3`
    # Defaults to false
    disableSSL: false

    # Template for the bucket name
    # preprod
    # cloud-id: aoep54jn7kndgo9aabqg
    # folder-id: aoestdavtgndti13rr1k
    bucket: deploy

    # Template for the path/name inside the bucket.
    # Default is `{{ .ProjectName }}/{{ .Tag }}`
    folder: "tools/{{ .ProjectName }}/{{ .Version }}"

    # You can add extra pre-existing files to the release.
    # The filename on the release will be the last part of the path (base). If
    # another file with the same name exists, the latest one found will be used.
    # Defaults to empty.
    # extra_files:
    #   - glob: ./path/to/file.txt
    #   - glob: ./glob/**/to/**/file/**/*
    #   - glob: ./glob/foo/to/bar/file/foobar/override_from_previous
  # -
  #   provider: gs
  #   bucket: goreleaser-bucket
  #   folder: "foo/bar/{{.Version}}"
  -
    provider: s3
    # preprod
    # cloud-id: aoep54jn7kndgo9aabqg
    # folder-id: aoestdavtgndti13rr1k
    bucket: deploy
    folder: "tools/{{ .ProjectName }}"
    endpoint: https://storage.cloud-preprod.yandex.net
